#服务器
server:
  port: 8888
#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.83.128:3306/my_blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: password
  redis:
    host: 192.168.83.128
    port: 6379
    password: 12345
  servlet:
    multipart:
      #单个文件的最大值
      max-file-size: 10MB
      #上传文件总的最大值
      max-request-size: 100MB
#mp配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  # 打印SQL语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: blog_
jwt:
  # 加密秘钥
  secret: 123456hyhblog!@#$$
  # token有效时长，1天，单位秒
  expire: 86400
thread:
  pool:
    corePoolSize: 5
    maxPoolSize: 20
    queueCapacity: 2000
    keepAliveSeconds: 60
#七牛云
qiniu:
  accessKey: 8aFandd9xxnq3VLiiVui2wJKwDWtWNk0B1HsXeQj
  secretKey: C0oj31fYatwDxZzw3cAb5KxPky9PTED07suxukhF
  bucket: hyh-images